poller:
  pollingRate: 15000
  maxMessagesPerPoll: 1
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hw08Mongo

    properties:
      hibernate:
        format_sql: true

    show-sql: true

  batch:
    job:
      enabled: false

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
logging:
  level:
    root: INFO
    ru.otus.hw: DEBUG
    org.springframework.integration: debug
    #org.springframework.jdbc.core.JdbcTemplate: INFO
    #org.springframework.data.mongodb.core: INFO
